# Created with WinGet Releaser using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: ractive.ff-rdp
PackageVersion: 0.4.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: ff-rdp.exe
  PortableCommandAlias: ff-rdp
InstallModes:
- silent
UpgradeBehavior: install
Protocols:
- https
ReleaseDate: 2026-10-04
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/ractive/ff-rdp/releases/download/v0.4.0/ff-rdp-v0.4.0-x86_64-pc-windows-msvc.zip
  InstallerSha256: A8324C1A5009A91B1EED96EB99F5C11B7C259EFA984B5ACF7E0E65B3657A5D84
- Architecture: arm64
  InstallerUrl: https://github.com/ractive/ff-rdp/releases/download/v0.4.0/ff-rdp-v0.4.0-aarch64-pc-windows-msvc.zip
  InstallerSha256: 55B8A03485D23B412CFFD1BF49405D0FCADFB6B1C551D8FAEA6BA1CEC7971B97
ManifestType: installer
ManifestVersion: 1.12.0
